image: node:16.20.1

stages:
  - build
  - test
  - plan
  - apply
  - destroy
  - db
  - db-undo
  - db-recreate
  - integration

variables:
  TG_IMAGE: alpine/terragrunt:1.5.2

cache:
  paths:
    - node_modules
    - lambda/node_modules
    - lambda/dist

build:
  stage: build
  script:
    - yarn clean
    - yarn build

test:
  stage: test
  script:
    - yarn lint
    - yarn unit

.plan:
  stage: plan
  image:
    name: $TG_IMAGE
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
    - terragrunt run-all plan --terragrunt-non-interactive
  when: manual

plan-preprod:
  extends:
    - .plan
  before_script:
    - cd terragrunt/live/preprod
  only:
    - develop

plan-prod:
  extends:
    - .plan
  before_script:
    - cd terragrunt/live/prod
  only:
    - master

.apply:
  stage: apply
  image:
    name: $TG_IMAGE
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terragrunt run-all apply --terragrunt-non-interactive
  # when: manual

apply-preprod:
  extends:
    - .apply
  before_script:
    - cd terragrunt/live/preprod
  only:
    - develop

apply-prod:
  extends:
    - .apply
  before_script:
    - cd terragrunt/live/prod
  only:
    - master

# commented out for safete needs, comment out only if required
# .destroy:
#   stage: destroy
#   image:
#     name: $TG_IMAGE
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
#   script:
#     - terragrunt run-all destroy --terragrunt-non-interactive
#   when: manual

# destroy-preprod:
#   extends:
#     - .destroy
#   before_script:
#     - cd terragrunt/live/preprod
#   only:
#     - develop

# destroy-prod:
#   extends:
#     - .destroy
#   before_script:
#     - cd terragrunt/live/prod
#   only:
#     - master

.db:
  stage: db

db-preprod:
  extends:
    - .db
  script:
    - yarn db-create-preprod
    - yarn db-migrate-preprod
    - yarn db-seeds-preprod
  only:
    - develop

db-prod:
  extends:
    - .db
  script:
    - yarn db-create-prod
    - yarn db-migrate-prod
    - yarn db-seeds-prod
  only:
    - master

.db-undo:
  stage: db-undo
  when: manual

db-undo-preprod:
  extends:
    - .db-undo
  script:
    - yarn db-undo-seeds-preprod
    - yarn db-undo-migrate-preprod
  only:
    - develop

db-undo-prod:
  extends:
    - .db-undo
  script:
    - yarn db-undo-seeds-prod
    - yarn db-undo-migrate-prod
  only:
    - master

.db-recreate:
  stage: db-recreate
  when: manual

db-recreate-preprod:
  extends:
    - .db-recreate
  script:
    - yarn db-drop-preprod
    - yarn db-create-preprod
    - yarn db-migrate-preprod
    - yarn db-seeds-preprod
  only:
    - develop

db-recreate-prod:
  extends:
    - .db-recreate
  script:
    - yarn db-drop-prod
    - yarn db-create-prod
    - yarn db-migrate-prod
    - yarn db-seeds-prod
  only:
    - master

.integration:
  stage: integration

integration-preprod:
  extends:
    - .integration
  script:
    - yarn integration-preprod
  only:
    - develop

integration-prod:
  extends:
    - .integration
  script:
    - yarn integration-prod
  only:
    - master
